### ISSUE TITLE
Project will not build if downloaded from github as zip.

### ISSUE THREAD

**Issue by fabiensanglard** [android/plaid#266] opened 2018-06-06 22:26 UTC
app/build.gradle features a git comman (line 25 which will fail:

`git rev-list --count HEAD`

**Comment by nickbutcher** [comment] 2018-06-08 11:40
You need to have git on your path. Closing as dupe of #17

**Comment by fabiensanglard** [comment] 2018-06-12 19:23
Even with git in the PATH, the git command will fail if there is no .git repo folder. 
This .git is missing if a user download the project as a zip file.

**Closed** 2019-11-26 11:18 UTC
