### ISSUE TITLE
SpannedGridLayoutManager takes extra blank space when you scroll fast

### ISSUE THREAD

**Issue by dn0myaraymond** [android/plaid#514] opened 2018-09-13 10:24 UTC
first thanks for the great spannedgridlayoutmanager this save my day. however i encountered some issue when you scrolling too fast(i implemented pagination). it takes extra blank space. i can't figure out what's the main cause of this 
here's the screenshot
![screenshot_20180913-180655_eyesup](https://user-images.githubusercontent.com/6575385/45482925-eb3b5b00-b781-11e8-9636-549a9576b3e1.jpg)

hope someone already solve this problem.

Thanks.

**Comment by Abror96** [comment] 2019-08-22 17:50
> first thanks for the great spannedgridlayoutmanager this save my day. however i encountered some issue when you scrolling too fast(i implemented pagination). it takes extra blank space. i can't figure out what's the main cause of this
> here's the screenshot
> ![screenshot_20180913-180655_eyesup](https://user-images.githubusercontent.com/6575385/45482925-eb3b5b00-b781-11e8-9636-549a9576b3e1.jpg)
> 
> hope someone already solve this problem.
> 
> Thanks.

did u find a solution?

**Comment by balavickey1192** [comment] 2019-10-10 10:51
Anyone solved this bug?

**Comment by dn0myaraymond** [comment] 2019-10-10 12:14
> > first thanks for the great spannedgridlayoutmanager this save my day. however i encountered some issue when you scrolling too fast(i implemented pagination). it takes extra blank space. i can't figure out what's the main cause of this
> > here's the screenshot
> > ![screenshot_20180913-180655_eyesup](https://user-images.githubusercontent.com/6575385/45482925-eb3b5b00-b781-11e8-9636-549a9576b3e1.jpg)
> > hope someone already solve this problem.
> > Thanks.
> 
> did u find a solution?



> Anyone solved this bug?

i ended up of using linearlayoutmanager with different view types,
maybe you can try this library https://github.com/Arasthel/SpannedGridLayoutManager, i think this is more stable now.

**Comment by gagan-3035** [comment] 2019-12-04 15:01
Hi any update on the same?

**Comment by pfmaggi** [comment] 2019-12-04 16:01
I'm closing this because I cannot reproduce the issue with Plaid.

**Closed by pfmaggi** 2019-12-04 16:01 UTC
