### ISSUE TITLE
Pixelated images on tablets

### ISSUE THREAD

**Issue by dictvm** [android/plaid#199] opened 2017-08-01 16:57 UTC
The graphics are pixelated on the Pixel C in the overview and after clicking on an image, even though the images are of a high resolution at the source. Here's an example:

![example](https://i.imgur.com/8BgAu4O_d.jpg?maxwidth=640&shape=thumb&fidelity=high)

**Comment by nickbutcher** [comment] 2017-08-01 17:40
Why do you think that the images are high res at source? I'm using the 800*600px size that I think it the max dribbble API offers.

The real fix here is to have a better layout on tablets, which is already covered by #174.

**Comment by dictvm** [comment] 2017-08-02 13:49
@nickbutcher I opened the site with the image from the linked screenshot in a browser and the browser displayed the image in a higher resolution without the excessive pixelation, that lead me to my conclusion. Thanks for the link to the issue. Maybe add a label "tablet" to it so non-devs can find it when they're searching for something tablet-related. :)

**Comment by keyboardsurfer** [comment] 2019-11-26 12:17
Duplicate of #199

**Closed by keyboardsurfer** 2019-11-26 12:17 UTC
